
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CITY = 15;
  public static final int INT_NUM = 16;
  public static final int S = 8;
  public static final int M = 11;
  public static final int ROUTE = 12;
  public static final int EOF = 0;
  public static final int C = 6;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int DD = 13;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int KCAL = 14;
  public static final int REAL_NUM = 17;
  public static final int KM = 9;
  public static final int TO = 7;
  public static final int ELEV = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "C",
  "TO",
  "S",
  "KM",
  "ELEV",
  "M",
  "ROUTE",
  "DD",
  "KCAL",
  "CITY",
  "INT_NUM",
  "REAL_NUM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("CITY");
		TT[16]=new String("INT_NUM");
		TT[8]=new String("S");
		TT[11]=new String("M");
		TT[12]=new String("ROUTE");
		TT[0]=new String("EOF");
		TT[6]=new String("C");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[13]=new String("DD");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[14]=new String("KCAL");
		TT[17]=new String("REAL_NUM");
		TT[9]=new String("KM");
		TT[7]=new String("TO");
		TT[10]=new String("ELEV");
	}
public String getTT(int i){return TT[i];}
}

